name: quizz_me
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  anim_search_bar: ^2.0.3
  smooth_page_indicator: ^1.0.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  provider: ^6.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  assets:
    - "assets/"
    - "assets/subjects/"
    - "assets/icons/"

  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Light.ttf
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Medium.ttf
        - asset: fonts/Comfortaa-SemiBold.ttf
        - asset: fonts/Comfortaa-Bold.ttf
